### ISSUE TITLE
Renaming `master` branch to `main`

### ISSUE THREAD

**Issue by laserkelvin** [intel/code-base-investigator#20]
We should rename `master` branch to `main` in accordance with new [Git defaults and more inclusive language](https://github.com/github/renaming).

**Comment by Pennycook** [comment]
I've just done this, and hopefully didn't mess anything up.

GitHub told me that local clones need to be updated manually, so I'm including the instructions for doing that below:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
